CREATE DATABASE ToDoHQ IF NOT EXISTS;
USE ToDoHQ;

CREATE TABLE Users (
    UserID INT AUTO_INCREMENT PRIMARY KEY,
    Username VARCHAR(50) UNIQUE NOT NULL,
    Email VARCHAR(50) UNIQUE NOT NULL,
    Password VARCHAR(255) NOT NULL
)

// TODO : add table for TODOs 
